### ISSUE TITLE
Any update on code release?

### ISSUE THREAD

**Issue by sachit-menon** [zengyan-97/X2-VLM#3]
Hi, thanks for this great work! I saw that the repo said code will be released in January; I was just wondering about the status of that. Would appreciate any update!

**Comment by yonatanbitton** [comment]
Waiting as well! :)

**Comment by Marco692** [comment]
Waiting as well! :)

**Comment by luong1409** [comment]
Waiting as well! :)))

**Comment by zengyan-97** [comment]
Hi, 
Thanks for your interest. 
I will try my best to release the code in the next few weeks.

**Comment by zengyan-97** [comment]
Hi, 
I am sorry for the late release...
All codes have been available now.
