### ISSUE TITLE
unable to download checkpoints

### ISSUE THREAD

**Issue by ae86208** [zengyan-97/X2-VLM#5]
![image](https://github.com/zengyan-97/X2-VLM/assets/7278690/e36f5830-830c-4a02-a130-e6c178072c33)

**Comment by ae86208** [comment]
seems like the link is internal of bytedance.

**Comment by zengyan-97** [comment]
hi, 
i have updated the links. 
please try again.

**Comment by ae86208** [comment]
It works this time, thx!
